<!DOCTYPEhtml>
<html>
    <head>
        <title>
            datatable
        </title>
        <link rel="stylesheet" href="http://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
        <script>
            $(document).ready( function () {
            $('#example').DataTable();
        } );
        </script>
    </head>
    <table id="example"class="display table table-bordered text-info"collapsing="0"width="100%">
        <thead>
            <tr>
                <th>NAME</th>
                <th>GENDER</th>
                <th>OCCUPATION</th>
                <th>NATIONALITY</th>
                <th>SALARY</th>
                <th>ESTATE</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Robert</td>
                <td>Male</td>
                <td>Web developer</td>
                <td>kenyan</td>
                <td>80000</td>
                <td>Gifted</td>
            </tr>
            <tr>
                <td>Mark</td>
                <td>Male</td>
                <td>drive</td>
                <td>kenyan</td>
                <td>50000</td>
                <td>Naivasha</td>
            </tr>
            <tr>
                <td>Jane</td>
                <td>FeMale</td>
                <td>hairdresser</td>
                <td>ugandan</td>
                <td>8000</td>
                <td>jersy</td>
            </tr>
            <tr>
                <td>Domii</td>
                <td>Male</td>
                <td>Kdf</td>
                <td>kenyan</td>
                <td>80000</td>
                <td>Nanyuki</td>
            </tr>
            <tr>
                <td>Ernest</td>
                <td>Male</td>
                <td>teacher</td>
                <td>tanzanian</td>
                <td>50000</td>
                <td>Gifted</td>
            </tr>
            <tr>
                <td>Job</td>
                <td>female</td>
                <td>teacher</td>
                <td>sudan</td>
                <td>40000</td>
                <td>kampere</td>
            </tr>
            <tr>
                <td>Jeff</td>
                <td>Male</td>
                <td>farmer</td>
                <td>burundi</td>
                <td>50000</td>
                <td>burdi</td>
            </tr>
            <tr>
                <td>tom</td>
                <td>feMale</td>
                <td>teacher</td>
                <td>ethiopian</td>
                <td>50000</td>
                <td>oxford</td>
            </tr>
            <tr>
                <td>kimutai</td>
                <td>Male</td>
                <td>engineer</td>
                <td>kenyan</td>
                <td>50000</td>
                <td>sarona</td>
            </tr>
            <tr>
                <td>ellie</td>
                <td>Male</td>
                <td>ict officer</td>
                <td>kenyan</td>
                <td>50000</td>
                <td>valleyroad</td>
            </tr>
            <tr>
                <td>vincent</td>
                <td>Male</td>
                <td>teacher</td>
                <td>somali</td>
                <td>50000</td>
                <td>turko</td>
            </tr>
            <tr>
                <td>mercy</td>
                <td>female</td>
                <td>operator</td>
                <td>mali</td>
                <td>46000</td>
                <td>kehanja</td>
            </tr>
            <tr>
                <td>David</td>
                <td>Male</td>
                <td>prophet</td>
                <td>kenyan</td>
                <td>500000</td>
                <td>nakuru</td>
            </tr>
            <tr>
                <td>linus</td>
                <td>Male</td>
                <td>driver</td>
                <td>congo</td>
                <td>70000</td>
                <td>kamara</td>
            </tr>
            <tr>
                <td>may</td>
                <td>feMale</td>
                <td>teacher</td>
                <td>tanzanian</td>
                <td>50000</td>
                <td>tana</td>
            </tr>
            <tr>
                <td>chebet</td>
                <td>female</td>
                <td>electrician</td>
                <td>kenyan</td>
                <td>80000</td>
                <td>uasingishu</td>
            </tr>
            <tr>
                <td>eduu</td>
                <td>female</td>
                <td>software</td>
                <td>mozambique</td>
                <td>67000</td>
                <td>mali</td>
            </tr>
            <tr>
                <td>joel</td>
                <td>Male</td>
                <td>teacher</td>
                <td>tanzanian</td>
                <td>70000</td>
                <td>apartment</td>
            </tr>
        </tbody>
    </table>
</html>
